// @generated — do not edit by hand.
#[cfg(feature = "axum")]
pub mod agent_skills;
#[cfg(feature = "axum")]
pub mod agents;
#[cfg(feature = "axum")]
pub mod catalogs;
#[cfg(feature = "axum")]
pub mod credentials;
#[cfg(feature = "axum")]
pub mod entity_tag_assignments;
#[cfg(feature = "axum")]
pub mod external_locations;
#[cfg(feature = "axum")]
pub mod functions;
#[cfg(feature = "axum")]
pub mod policies;
#[cfg(feature = "axum")]
pub mod providers;
#[cfg(feature = "axum")]
pub mod recipients;
#[cfg(feature = "axum")]
pub mod schemas;
#[cfg(feature = "axum")]
pub mod shares;
#[cfg(feature = "axum")]
pub mod staging_tables;
#[cfg(feature = "axum")]
pub mod tables;
#[cfg(feature = "axum")]
pub mod tag_policies;
#[cfg(feature = "axum")]
pub mod temporary_credentials;
#[cfg(feature = "axum")]
pub mod volumes;
