// @generated by buffa-codegen. DO NOT EDIT.

/// A single SQL query to run.
///
/// Field numbers 1-4 intentionally match `hydrofoil.query.v1.RunQueryRequest` so
/// a downstream host can implement this contract without a wire-shape mismatch.
///
/// This contract deliberately carries no validation annotations (buf.validate /
/// field_behavior): it states message SHAPES only. `sql` is required and `limit`
/// is an optional row cap, but enforcement lives in the implementing runner's own
/// proto/server — mangrove generates TypeScript types, not a validating server.
#[derive(Clone, PartialEq, Default)]
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[serde(default)]
pub struct RunQueryRequest {
    /// The SQL to execute. Required.
    ///
    /// Field 1: `sql`
    #[serde(
        rename = "sql",
        with = "::buffa::json_helpers::proto_string",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_empty_str"
    )]
    pub sql: ::buffa::alloc::string::String,
    /// Optional row cap. An implementing runner may clamp this to its own maximum;
    /// when omitted the runner applies its own default limit.
    ///
    /// Field 2: `limit`
    #[serde(
        rename = "limit",
        with = "::buffa::json_helpers::opt_uint32",
        skip_serializing_if = "::core::option::Option::is_none"
    )]
    pub limit: ::core::option::Option<u32>,
    /// Optional session default namespace for bare table names in `sql`.
    /// Fully-qualified `catalog.schema.table` references resolve regardless.
    ///
    /// Field 3: `catalog`
    #[serde(rename = "catalog", skip_serializing_if = "::core::option::Option::is_none")]
    pub catalog: ::core::option::Option<::buffa::alloc::string::String>,
    /// Field 4: `schema`
    #[serde(rename = "schema", skip_serializing_if = "::core::option::Option::is_none")]
    pub schema: ::core::option::Option<::buffa::alloc::string::String>,
    #[serde(skip)]
    #[doc(hidden)]
    pub __buffa_unknown_fields: ::buffa::UnknownFields,
}
impl ::core::fmt::Debug for RunQueryRequest {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("RunQueryRequest")
            .field("sql", &self.sql)
            .field("limit", &self.limit)
            .field("catalog", &self.catalog)
            .field("schema", &self.schema)
            .finish()
    }
}
impl RunQueryRequest {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/open_lakehouse.query.v1.RunQueryRequest";
}
impl RunQueryRequest {
    #[must_use = "with_* setters return `self` by value; assign or chain the result"]
    #[inline]
    ///Sets [`Self::limit`] to `Some(value)`, consuming and returning `self`.
    pub fn with_limit(mut self, value: u32) -> Self {
        self.limit = Some(value);
        self
    }
    #[must_use = "with_* setters return `self` by value; assign or chain the result"]
    #[inline]
    ///Sets [`Self::catalog`] to `Some(value)`, consuming and returning `self`.
    pub fn with_catalog(
        mut self,
        value: impl Into<::buffa::alloc::string::String>,
    ) -> Self {
        self.catalog = Some(value.into());
        self
    }
    #[must_use = "with_* setters return `self` by value; assign or chain the result"]
    #[inline]
    ///Sets [`Self::schema`] to `Some(value)`, consuming and returning `self`.
    pub fn with_schema(
        mut self,
        value: impl Into<::buffa::alloc::string::String>,
    ) -> Self {
        self.schema = Some(value.into());
        self
    }
}
impl ::buffa::DefaultInstance for RunQueryRequest {
    fn default_instance() -> &'static Self {
        static VALUE: ::buffa::__private::OnceBox<RunQueryRequest> = ::buffa::__private::OnceBox::new();
        VALUE.get_or_init(|| ::buffa::alloc::boxed::Box::new(Self::default()))
    }
}
impl ::buffa::MessageName for RunQueryRequest {
    const PACKAGE: &'static str = "open_lakehouse.query.v1";
    const NAME: &'static str = "RunQueryRequest";
    const FULL_NAME: &'static str = "open_lakehouse.query.v1.RunQueryRequest";
    const TYPE_URL: &'static str = "type.googleapis.com/open_lakehouse.query.v1.RunQueryRequest";
}
impl ::buffa::Message for RunQueryRequest {
    /// Returns the total encoded size in bytes.
    ///
    /// The result is a `u32`; the protobuf specification requires all
    /// messages to fit within 2 GiB (2,147,483,647 bytes), so a
    /// compliant message will never overflow this type.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u32;
        if !self.sql.is_empty() {
            size += 1u32 + ::buffa::types::string_encoded_len(&self.sql) as u32;
        }
        if let Some(v) = self.limit {
            size += 1u32 + ::buffa::types::uint32_encoded_len(v) as u32;
        }
        if let Some(ref v) = self.catalog {
            size += 1u32 + ::buffa::types::string_encoded_len(v) as u32;
        }
        if let Some(ref v) = self.schema {
            size += 1u32 + ::buffa::types::string_encoded_len(v) as u32;
        }
        size += self.__buffa_unknown_fields.encoded_len() as u32;
        size
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.sql.is_empty() {
            ::buffa::encoding::Tag::new(
                    1u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::types::encode_string(&self.sql, buf);
        }
        if let Some(v) = self.limit {
            ::buffa::encoding::Tag::new(2u32, ::buffa::encoding::WireType::Varint)
                .encode(buf);
            ::buffa::types::encode_uint32(v, buf);
        }
        if let Some(ref v) = self.catalog {
            ::buffa::encoding::Tag::new(
                    3u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::types::encode_string(v, buf);
        }
        if let Some(ref v) = self.schema {
            ::buffa::encoding::Tag::new(
                    4u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::types::encode_string(v, buf);
        }
        self.__buffa_unknown_fields.write_to(buf);
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        depth: u32,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                if tag.wire_type() != ::buffa::encoding::WireType::LengthDelimited {
                    return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                        field_number: 1u32,
                        expected: 2u8,
                        actual: tag.wire_type() as u8,
                    });
                }
                ::buffa::types::merge_string(&mut self.sql, buf)?;
            }
            2u32 => {
                if tag.wire_type() != ::buffa::encoding::WireType::Varint {
                    return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                        field_number: 2u32,
                        expected: 0u8,
                        actual: tag.wire_type() as u8,
                    });
                }
                self.limit = ::core::option::Option::Some(
                    ::buffa::types::decode_uint32(buf)?,
                );
            }
            3u32 => {
                if tag.wire_type() != ::buffa::encoding::WireType::LengthDelimited {
                    return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                        field_number: 3u32,
                        expected: 2u8,
                        actual: tag.wire_type() as u8,
                    });
                }
                ::buffa::types::merge_string(
                    self.catalog.get_or_insert_with(::buffa::alloc::string::String::new),
                    buf,
                )?;
            }
            4u32 => {
                if tag.wire_type() != ::buffa::encoding::WireType::LengthDelimited {
                    return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                        field_number: 4u32,
                        expected: 2u8,
                        actual: tag.wire_type() as u8,
                    });
                }
                ::buffa::types::merge_string(
                    self.schema.get_or_insert_with(::buffa::alloc::string::String::new),
                    buf,
                )?;
            }
            _ => {
                self.__buffa_unknown_fields
                    .push(::buffa::encoding::decode_unknown_field(tag, buf, depth)?);
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.sql.clear();
        self.limit = ::core::option::Option::None;
        self.catalog = ::core::option::Option::None;
        self.schema = ::core::option::Option::None;
        self.__buffa_unknown_fields.clear();
    }
}
impl ::buffa::ExtensionSet for RunQueryRequest {
    const PROTO_FQN: &'static str = "open_lakehouse.query.v1.RunQueryRequest";
    fn unknown_fields(&self) -> &::buffa::UnknownFields {
        &self.__buffa_unknown_fields
    }
    fn unknown_fields_mut(&mut self) -> &mut ::buffa::UnknownFields {
        &mut self.__buffa_unknown_fields
    }
}
impl ::buffa::json_helpers::ProtoElemJson for RunQueryRequest {
    fn serialize_proto_json<S: ::serde::Serializer>(
        v: &Self,
        s: S,
    ) -> ::core::result::Result<S::Ok, S::Error> {
        ::serde::Serialize::serialize(v, s)
    }
    fn deserialize_proto_json<'de, D: ::serde::Deserializer<'de>>(
        d: D,
    ) -> ::core::result::Result<Self, D::Error> {
        <Self as ::serde::Deserialize>::deserialize(d)
    }
}
#[doc(hidden)]
pub const __RUN_QUERY_REQUEST_JSON_ANY: ::buffa::type_registry::JsonAnyEntry = ::buffa::type_registry::JsonAnyEntry {
    type_url: "type.googleapis.com/open_lakehouse.query.v1.RunQueryRequest",
    to_json: ::buffa::type_registry::any_to_json::<RunQueryRequest>,
    from_json: ::buffa::type_registry::any_from_json::<RunQueryRequest>,
    is_wkt: false,
};
/// One chunk of the result stream: a self-contained Arrow IPC stream for one
/// record batch (see the package docs for framing).
#[derive(Clone, PartialEq, Default)]
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[serde(default)]
pub struct RunQueryResponse {
    /// Arrow IPC stream bytes for one record batch (schema + batch + EOS). The
    /// first message's bytes carry the schema, so an empty result still yields one
    /// schema-only message. Feeds `ArrowResultStore.append(ipc)` directly.
    ///
    /// Field 1: `arrow_ipc`
    #[serde(
        rename = "arrowIpc",
        alias = "arrow_ipc",
        with = "::buffa::json_helpers::bytes",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_empty_bytes"
    )]
    pub arrow_ipc: ::buffa::alloc::vec::Vec<u8>,
    /// Rows in this chunk, so the client can show progress without decoding.
    ///
    /// Field 2: `num_rows`
    #[serde(
        rename = "numRows",
        alias = "num_rows",
        with = "::buffa::json_helpers::uint64",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_zero_u64"
    )]
    pub num_rows: u64,
    #[serde(skip)]
    #[doc(hidden)]
    pub __buffa_unknown_fields: ::buffa::UnknownFields,
}
impl ::core::fmt::Debug for RunQueryResponse {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("RunQueryResponse")
            .field("arrow_ipc", &self.arrow_ipc)
            .field("num_rows", &self.num_rows)
            .finish()
    }
}
impl RunQueryResponse {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/open_lakehouse.query.v1.RunQueryResponse";
}
impl ::buffa::DefaultInstance for RunQueryResponse {
    fn default_instance() -> &'static Self {
        static VALUE: ::buffa::__private::OnceBox<RunQueryResponse> = ::buffa::__private::OnceBox::new();
        VALUE.get_or_init(|| ::buffa::alloc::boxed::Box::new(Self::default()))
    }
}
impl ::buffa::MessageName for RunQueryResponse {
    const PACKAGE: &'static str = "open_lakehouse.query.v1";
    const NAME: &'static str = "RunQueryResponse";
    const FULL_NAME: &'static str = "open_lakehouse.query.v1.RunQueryResponse";
    const TYPE_URL: &'static str = "type.googleapis.com/open_lakehouse.query.v1.RunQueryResponse";
}
impl ::buffa::Message for RunQueryResponse {
    /// Returns the total encoded size in bytes.
    ///
    /// The result is a `u32`; the protobuf specification requires all
    /// messages to fit within 2 GiB (2,147,483,647 bytes), so a
    /// compliant message will never overflow this type.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u32;
        if !self.arrow_ipc.is_empty() {
            size += 1u32 + ::buffa::types::bytes_encoded_len(&self.arrow_ipc) as u32;
        }
        if self.num_rows != 0u64 {
            size += 1u32 + ::buffa::types::uint64_encoded_len(self.num_rows) as u32;
        }
        size += self.__buffa_unknown_fields.encoded_len() as u32;
        size
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.arrow_ipc.is_empty() {
            ::buffa::encoding::Tag::new(
                    1u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::types::encode_bytes(&self.arrow_ipc, buf);
        }
        if self.num_rows != 0u64 {
            ::buffa::encoding::Tag::new(2u32, ::buffa::encoding::WireType::Varint)
                .encode(buf);
            ::buffa::types::encode_uint64(self.num_rows, buf);
        }
        self.__buffa_unknown_fields.write_to(buf);
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        depth: u32,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                if tag.wire_type() != ::buffa::encoding::WireType::LengthDelimited {
                    return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                        field_number: 1u32,
                        expected: 2u8,
                        actual: tag.wire_type() as u8,
                    });
                }
                ::buffa::types::merge_bytes(&mut self.arrow_ipc, buf)?;
            }
            2u32 => {
                if tag.wire_type() != ::buffa::encoding::WireType::Varint {
                    return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                        field_number: 2u32,
                        expected: 0u8,
                        actual: tag.wire_type() as u8,
                    });
                }
                self.num_rows = ::buffa::types::decode_uint64(buf)?;
            }
            _ => {
                self.__buffa_unknown_fields
                    .push(::buffa::encoding::decode_unknown_field(tag, buf, depth)?);
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.arrow_ipc.clear();
        self.num_rows = 0u64;
        self.__buffa_unknown_fields.clear();
    }
}
impl ::buffa::ExtensionSet for RunQueryResponse {
    const PROTO_FQN: &'static str = "open_lakehouse.query.v1.RunQueryResponse";
    fn unknown_fields(&self) -> &::buffa::UnknownFields {
        &self.__buffa_unknown_fields
    }
    fn unknown_fields_mut(&mut self) -> &mut ::buffa::UnknownFields {
        &mut self.__buffa_unknown_fields
    }
}
impl ::buffa::json_helpers::ProtoElemJson for RunQueryResponse {
    fn serialize_proto_json<S: ::serde::Serializer>(
        v: &Self,
        s: S,
    ) -> ::core::result::Result<S::Ok, S::Error> {
        ::serde::Serialize::serialize(v, s)
    }
    fn deserialize_proto_json<'de, D: ::serde::Deserializer<'de>>(
        d: D,
    ) -> ::core::result::Result<Self, D::Error> {
        <Self as ::serde::Deserialize>::deserialize(d)
    }
}
#[doc(hidden)]
pub const __RUN_QUERY_RESPONSE_JSON_ANY: ::buffa::type_registry::JsonAnyEntry = ::buffa::type_registry::JsonAnyEntry {
    type_url: "type.googleapis.com/open_lakehouse.query.v1.RunQueryResponse",
    to_json: ::buffa::type_registry::any_to_json::<RunQueryResponse>,
    from_json: ::buffa::type_registry::any_from_json::<RunQueryResponse>,
    is_wkt: false,
};
#[allow(
    non_camel_case_types,
    dead_code,
    unused_imports,
    unused_qualifications,
    clippy::derivable_impls,
    clippy::match_single_binding,
    clippy::uninlined_format_args,
    clippy::doc_lazy_continuation,
    clippy::module_inception
)]
pub mod __buffa {
    #[allow(unused_imports)]
    use super::*;
    pub mod view {
        #[allow(unused_imports)]
        use super::*;
        /// A single SQL query to run.
        ///
        /// Field numbers 1-4 intentionally match `hydrofoil.query.v1.RunQueryRequest` so
        /// a downstream host can implement this contract without a wire-shape mismatch.
        ///
        /// This contract deliberately carries no validation annotations (buf.validate /
        /// field_behavior): it states message SHAPES only. `sql` is required and `limit`
        /// is an optional row cap, but enforcement lives in the implementing runner's own
        /// proto/server — mangrove generates TypeScript types, not a validating server.
        #[derive(Clone, Debug, Default)]
        pub struct RunQueryRequestView<'a> {
            /// The SQL to execute. Required.
            ///
            /// Field 1: `sql`
            pub sql: &'a str,
            /// Optional row cap. An implementing runner may clamp this to its own maximum;
            /// when omitted the runner applies its own default limit.
            ///
            /// Field 2: `limit`
            pub limit: ::core::option::Option<u32>,
            /// Optional session default namespace for bare table names in `sql`.
            /// Fully-qualified `catalog.schema.table` references resolve regardless.
            ///
            /// Field 3: `catalog`
            pub catalog: ::core::option::Option<&'a str>,
            /// Field 4: `schema`
            pub schema: ::core::option::Option<&'a str>,
            pub __buffa_unknown_fields: ::buffa::UnknownFieldsView<'a>,
        }
        impl<'a> RunQueryRequestView<'a> {
            /// Decode from `buf`, enforcing a recursion depth limit for nested messages.
            ///
            /// Called by [`::buffa::MessageView::decode_view`] with [`::buffa::RECURSION_LIMIT`]
            /// and by generated sub-message decode arms with `depth - 1`.
            ///
            /// **Not part of the public API.** Named with a leading underscore to
            /// signal that it is for generated-code use only.
            #[doc(hidden)]
            pub fn _decode_depth(
                buf: &'a [u8],
                depth: u32,
            ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
                let mut view = Self::default();
                view._merge_into_view(buf, depth)?;
                ::core::result::Result::Ok(view)
            }
            /// Merge fields from `buf` into this view (proto merge semantics).
            ///
            /// Repeated fields append; singular fields last-wins; singular
            /// MESSAGE fields merge recursively. Used by sub-message decode
            /// arms when the same field appears multiple times on the wire.
            ///
            /// **Not part of the public API.**
            #[doc(hidden)]
            pub fn _merge_into_view(
                &mut self,
                buf: &'a [u8],
                depth: u32,
            ) -> ::core::result::Result<(), ::buffa::DecodeError> {
                let _ = depth;
                #[allow(unused_variables)]
                let view = self;
                let mut cur: &'a [u8] = buf;
                while !cur.is_empty() {
                    let before_tag = cur;
                    let tag = ::buffa::encoding::Tag::decode(&mut cur)?;
                    match tag.field_number() {
                        1u32 => {
                            if tag.wire_type()
                                != ::buffa::encoding::WireType::LengthDelimited
                            {
                                return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                                    field_number: 1u32,
                                    expected: 2u8,
                                    actual: tag.wire_type() as u8,
                                });
                            }
                            view.sql = ::buffa::types::borrow_str(&mut cur)?;
                        }
                        2u32 => {
                            if tag.wire_type() != ::buffa::encoding::WireType::Varint {
                                return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                                    field_number: 2u32,
                                    expected: 0u8,
                                    actual: tag.wire_type() as u8,
                                });
                            }
                            view.limit = Some(::buffa::types::decode_uint32(&mut cur)?);
                        }
                        3u32 => {
                            if tag.wire_type()
                                != ::buffa::encoding::WireType::LengthDelimited
                            {
                                return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                                    field_number: 3u32,
                                    expected: 2u8,
                                    actual: tag.wire_type() as u8,
                                });
                            }
                            view.catalog = Some(::buffa::types::borrow_str(&mut cur)?);
                        }
                        4u32 => {
                            if tag.wire_type()
                                != ::buffa::encoding::WireType::LengthDelimited
                            {
                                return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                                    field_number: 4u32,
                                    expected: 2u8,
                                    actual: tag.wire_type() as u8,
                                });
                            }
                            view.schema = Some(::buffa::types::borrow_str(&mut cur)?);
                        }
                        _ => {
                            ::buffa::encoding::skip_field_depth(tag, &mut cur, depth)?;
                            let span_len = before_tag.len() - cur.len();
                            view.__buffa_unknown_fields
                                .push_raw(&before_tag[..span_len]);
                        }
                    }
                }
                ::core::result::Result::Ok(())
            }
        }
        impl<'a> ::buffa::MessageView<'a> for RunQueryRequestView<'a> {
            type Owned = super::super::RunQueryRequest;
            fn decode_view(
                buf: &'a [u8],
            ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
                Self::_decode_depth(buf, ::buffa::RECURSION_LIMIT)
            }
            fn decode_view_with_limit(
                buf: &'a [u8],
                depth: u32,
            ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
                Self::_decode_depth(buf, depth)
            }
            fn to_owned_message(&self) -> super::super::RunQueryRequest {
                self.to_owned_from_source(None)
            }
            #[allow(clippy::useless_conversion, clippy::needless_update)]
            fn to_owned_from_source(
                &self,
                __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
            ) -> super::super::RunQueryRequest {
                #[allow(unused_imports)]
                use ::buffa::alloc::string::ToString as _;
                let _ = __buffa_src;
                super::super::RunQueryRequest {
                    sql: self.sql.to_string(),
                    limit: self.limit,
                    catalog: self.catalog.map(|s| s.to_string()),
                    schema: self.schema.map(|s| s.to_string()),
                    __buffa_unknown_fields: self
                        .__buffa_unknown_fields
                        .to_owned()
                        .unwrap_or_default()
                        .into(),
                    ..::core::default::Default::default()
                }
            }
        }
        impl<'a> ::buffa::ViewEncode<'a> for RunQueryRequestView<'a> {
            #[allow(clippy::needless_borrow, clippy::let_and_return)]
            fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
                #[allow(unused_imports)]
                use ::buffa::Enumeration as _;
                let mut size = 0u32;
                if !self.sql.is_empty() {
                    size += 1u32 + ::buffa::types::string_encoded_len(&self.sql) as u32;
                }
                if let Some(v) = self.limit {
                    size += 1u32 + ::buffa::types::uint32_encoded_len(v) as u32;
                }
                if let Some(ref v) = self.catalog {
                    size += 1u32 + ::buffa::types::string_encoded_len(v) as u32;
                }
                if let Some(ref v) = self.schema {
                    size += 1u32 + ::buffa::types::string_encoded_len(v) as u32;
                }
                size += self.__buffa_unknown_fields.encoded_len() as u32;
                size
            }
            #[allow(clippy::needless_borrow)]
            fn write_to(
                &self,
                _cache: &mut ::buffa::SizeCache,
                buf: &mut impl ::buffa::bytes::BufMut,
            ) {
                #[allow(unused_imports)]
                use ::buffa::Enumeration as _;
                if !self.sql.is_empty() {
                    ::buffa::encoding::Tag::new(
                            1u32,
                            ::buffa::encoding::WireType::LengthDelimited,
                        )
                        .encode(buf);
                    ::buffa::types::encode_string(&self.sql, buf);
                }
                if let Some(v) = self.limit {
                    ::buffa::encoding::Tag::new(
                            2u32,
                            ::buffa::encoding::WireType::Varint,
                        )
                        .encode(buf);
                    ::buffa::types::encode_uint32(v, buf);
                }
                if let Some(ref v) = self.catalog {
                    ::buffa::encoding::Tag::new(
                            3u32,
                            ::buffa::encoding::WireType::LengthDelimited,
                        )
                        .encode(buf);
                    ::buffa::types::encode_string(v, buf);
                }
                if let Some(ref v) = self.schema {
                    ::buffa::encoding::Tag::new(
                            4u32,
                            ::buffa::encoding::WireType::LengthDelimited,
                        )
                        .encode(buf);
                    ::buffa::types::encode_string(v, buf);
                }
                self.__buffa_unknown_fields.write_to(buf);
            }
        }
        /// Serializes this view as protobuf JSON.
        ///
        /// Implicit-presence fields with default values are omitted, `required`
        /// fields are always emitted, explicit-presence (`optional`) fields are
        /// emitted only when set, bytes fields are base64-encoded, and enum
        /// values are their proto name strings.
        ///
        /// This impl uses `serialize_map(None)` because the number of emitted
        /// fields depends on default-omission rules; serializers that require
        /// known map lengths (e.g. `bincode`) will return a runtime error.
        /// Use the owned message type for those formats.
        impl<'__a> ::serde::Serialize for RunQueryRequestView<'__a> {
            fn serialize<__S: ::serde::Serializer>(
                &self,
                __s: __S,
            ) -> ::core::result::Result<__S::Ok, __S::Error> {
                use ::serde::ser::SerializeMap as _;
                let mut __map = __s.serialize_map(::core::option::Option::None)?;
                if !::buffa::json_helpers::skip_if::is_empty_str(self.sql) {
                    __map.serialize_entry("sql", self.sql)?;
                }
                if let ::core::option::Option::Some(__v) = self.limit {
                    struct _W(u32);
                    impl ::serde::Serialize for _W {
                        fn serialize<__S: ::serde::Serializer>(
                            &self,
                            __s: __S,
                        ) -> ::core::result::Result<__S::Ok, __S::Error> {
                            ::buffa::json_helpers::uint32::serialize(&self.0, __s)
                        }
                    }
                    __map.serialize_entry("limit", &_W(__v))?;
                }
                if let ::core::option::Option::Some(__v) = self.catalog {
                    __map.serialize_entry("catalog", __v)?;
                }
                if let ::core::option::Option::Some(__v) = self.schema {
                    __map.serialize_entry("schema", __v)?;
                }
                __map.end()
            }
        }
        impl<'a> ::buffa::MessageName for RunQueryRequestView<'a> {
            const PACKAGE: &'static str = "open_lakehouse.query.v1";
            const NAME: &'static str = "RunQueryRequest";
            const FULL_NAME: &'static str = "open_lakehouse.query.v1.RunQueryRequest";
            const TYPE_URL: &'static str = "type.googleapis.com/open_lakehouse.query.v1.RunQueryRequest";
        }
        impl<'v> ::buffa::DefaultViewInstance for RunQueryRequestView<'v> {
            fn default_view_instance<'a>() -> &'a Self
            where
                Self: 'a,
            {
                static VALUE: ::buffa::__private::OnceBox<
                    RunQueryRequestView<'static>,
                > = ::buffa::__private::OnceBox::new();
                VALUE
                    .get_or_init(|| ::buffa::alloc::boxed::Box::new(
                        <RunQueryRequestView<'static>>::default(),
                    ))
            }
        }
        impl ::buffa::ViewReborrow for RunQueryRequestView<'static> {
            type Reborrowed<'b> = RunQueryRequestView<'b>;
            fn reborrow<'b>(this: &'b Self) -> &'b Self::Reborrowed<'b> {
                this
            }
        }
        /** Self-contained, `'static` owned view of a `RunQueryRequest` message.

 Wraps [`::buffa::OwnedView`]`<`[`RunQueryRequestView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`RunQueryRequestView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
        #[derive(Clone, Debug)]
        pub struct RunQueryRequestOwnedView(
            ::buffa::OwnedView<RunQueryRequestView<'static>>,
        );
        impl RunQueryRequestOwnedView {
            /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
            ///
            /// The view borrows directly from the buffer's data; the buffer is
            /// retained inside the returned handle.
            ///
            /// # Errors
            ///
            /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
            /// protobuf data.
            pub fn decode(
                bytes: ::buffa::bytes::Bytes,
            ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
                ::core::result::Result::Ok(
                    RunQueryRequestOwnedView(::buffa::OwnedView::decode(bytes)?),
                )
            }
            /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
            /// max message size).
            ///
            /// # Errors
            ///
            /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
            /// exceeds the configured limits.
            pub fn decode_with_options(
                bytes: ::buffa::bytes::Bytes,
                opts: &::buffa::DecodeOptions,
            ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
                ::core::result::Result::Ok(
                    RunQueryRequestOwnedView(
                        ::buffa::OwnedView::decode_with_options(bytes, opts)?,
                    ),
                )
            }
            /// Build from an owned message via an encode → decode round-trip.
            ///
            /// # Errors
            ///
            /// Returns [`::buffa::DecodeError`] if the re-encoded bytes are
            /// somehow invalid (should not happen for well-formed messages).
            pub fn from_owned(
                msg: &super::super::RunQueryRequest,
            ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
                ::core::result::Result::Ok(
                    RunQueryRequestOwnedView(::buffa::OwnedView::from_owned(msg)?),
                )
            }
            /// Borrow the full [`RunQueryRequestView`] with its lifetime tied to `&self`.
            #[must_use]
            pub fn view(&self) -> &RunQueryRequestView<'_> {
                self.0.reborrow()
            }
            /// Convert to the owned message type.
            #[must_use]
            pub fn to_owned_message(&self) -> super::super::RunQueryRequest {
                self.0.to_owned_message()
            }
            /// The underlying bytes buffer.
            #[must_use]
            pub fn bytes(&self) -> &::buffa::bytes::Bytes {
                self.0.bytes()
            }
            /// Consume the handle, returning the underlying bytes buffer.
            #[must_use]
            pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
                self.0.into_bytes()
            }
            /// The SQL to execute. Required.
            ///
            /// Field 1: `sql`
            #[must_use]
            pub fn sql(&self) -> &'_ str {
                self.0.reborrow().sql
            }
            /// Optional row cap. An implementing runner may clamp this to its own maximum;
            /// when omitted the runner applies its own default limit.
            ///
            /// Field 2: `limit`
            #[must_use]
            pub fn limit(&self) -> ::core::option::Option<u32> {
                self.0.reborrow().limit
            }
            /// Optional session default namespace for bare table names in `sql`.
            /// Fully-qualified `catalog.schema.table` references resolve regardless.
            ///
            /// Field 3: `catalog`
            #[must_use]
            pub fn catalog(&self) -> ::core::option::Option<&'_ str> {
                self.0.reborrow().catalog
            }
            /// Field 4: `schema`
            #[must_use]
            pub fn schema(&self) -> ::core::option::Option<&'_ str> {
                self.0.reborrow().schema
            }
        }
        impl ::core::convert::From<::buffa::OwnedView<RunQueryRequestView<'static>>>
        for RunQueryRequestOwnedView {
            fn from(inner: ::buffa::OwnedView<RunQueryRequestView<'static>>) -> Self {
                RunQueryRequestOwnedView(inner)
            }
        }
        impl ::core::convert::From<RunQueryRequestOwnedView>
        for ::buffa::OwnedView<RunQueryRequestView<'static>> {
            fn from(wrapper: RunQueryRequestOwnedView) -> Self {
                wrapper.0
            }
        }
        impl ::core::convert::AsRef<::buffa::OwnedView<RunQueryRequestView<'static>>>
        for RunQueryRequestOwnedView {
            fn as_ref(&self) -> &::buffa::OwnedView<RunQueryRequestView<'static>> {
                &self.0
            }
        }
        impl ::buffa::HasMessageView for super::super::RunQueryRequest {
            type View<'a> = RunQueryRequestView<'a>;
            type ViewHandle = RunQueryRequestOwnedView;
        }
        impl ::serde::Serialize for RunQueryRequestOwnedView {
            fn serialize<__S: ::serde::Serializer>(
                &self,
                __s: __S,
            ) -> ::core::result::Result<__S::Ok, __S::Error> {
                ::serde::Serialize::serialize(&self.0, __s)
            }
        }
        /// One chunk of the result stream: a self-contained Arrow IPC stream for one
        /// record batch (see the package docs for framing).
        #[derive(Clone, Debug, Default)]
        pub struct RunQueryResponseView<'a> {
            /// Arrow IPC stream bytes for one record batch (schema + batch + EOS). The
            /// first message's bytes carry the schema, so an empty result still yields one
            /// schema-only message. Feeds `ArrowResultStore.append(ipc)` directly.
            ///
            /// Field 1: `arrow_ipc`
            pub arrow_ipc: &'a [u8],
            /// Rows in this chunk, so the client can show progress without decoding.
            ///
            /// Field 2: `num_rows`
            pub num_rows: u64,
            pub __buffa_unknown_fields: ::buffa::UnknownFieldsView<'a>,
        }
        impl<'a> RunQueryResponseView<'a> {
            /// Decode from `buf`, enforcing a recursion depth limit for nested messages.
            ///
            /// Called by [`::buffa::MessageView::decode_view`] with [`::buffa::RECURSION_LIMIT`]
            /// and by generated sub-message decode arms with `depth - 1`.
            ///
            /// **Not part of the public API.** Named with a leading underscore to
            /// signal that it is for generated-code use only.
            #[doc(hidden)]
            pub fn _decode_depth(
                buf: &'a [u8],
                depth: u32,
            ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
                let mut view = Self::default();
                view._merge_into_view(buf, depth)?;
                ::core::result::Result::Ok(view)
            }
            /// Merge fields from `buf` into this view (proto merge semantics).
            ///
            /// Repeated fields append; singular fields last-wins; singular
            /// MESSAGE fields merge recursively. Used by sub-message decode
            /// arms when the same field appears multiple times on the wire.
            ///
            /// **Not part of the public API.**
            #[doc(hidden)]
            pub fn _merge_into_view(
                &mut self,
                buf: &'a [u8],
                depth: u32,
            ) -> ::core::result::Result<(), ::buffa::DecodeError> {
                let _ = depth;
                #[allow(unused_variables)]
                let view = self;
                let mut cur: &'a [u8] = buf;
                while !cur.is_empty() {
                    let before_tag = cur;
                    let tag = ::buffa::encoding::Tag::decode(&mut cur)?;
                    match tag.field_number() {
                        1u32 => {
                            if tag.wire_type()
                                != ::buffa::encoding::WireType::LengthDelimited
                            {
                                return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                                    field_number: 1u32,
                                    expected: 2u8,
                                    actual: tag.wire_type() as u8,
                                });
                            }
                            view.arrow_ipc = ::buffa::types::borrow_bytes(&mut cur)?;
                        }
                        2u32 => {
                            if tag.wire_type() != ::buffa::encoding::WireType::Varint {
                                return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                                    field_number: 2u32,
                                    expected: 0u8,
                                    actual: tag.wire_type() as u8,
                                });
                            }
                            view.num_rows = ::buffa::types::decode_uint64(&mut cur)?;
                        }
                        _ => {
                            ::buffa::encoding::skip_field_depth(tag, &mut cur, depth)?;
                            let span_len = before_tag.len() - cur.len();
                            view.__buffa_unknown_fields
                                .push_raw(&before_tag[..span_len]);
                        }
                    }
                }
                ::core::result::Result::Ok(())
            }
        }
        impl<'a> ::buffa::MessageView<'a> for RunQueryResponseView<'a> {
            type Owned = super::super::RunQueryResponse;
            fn decode_view(
                buf: &'a [u8],
            ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
                Self::_decode_depth(buf, ::buffa::RECURSION_LIMIT)
            }
            fn decode_view_with_limit(
                buf: &'a [u8],
                depth: u32,
            ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
                Self::_decode_depth(buf, depth)
            }
            fn to_owned_message(&self) -> super::super::RunQueryResponse {
                self.to_owned_from_source(None)
            }
            #[allow(clippy::useless_conversion, clippy::needless_update)]
            fn to_owned_from_source(
                &self,
                __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
            ) -> super::super::RunQueryResponse {
                #[allow(unused_imports)]
                use ::buffa::alloc::string::ToString as _;
                let _ = __buffa_src;
                super::super::RunQueryResponse {
                    arrow_ipc: (self.arrow_ipc).to_vec(),
                    num_rows: self.num_rows,
                    __buffa_unknown_fields: self
                        .__buffa_unknown_fields
                        .to_owned()
                        .unwrap_or_default()
                        .into(),
                    ..::core::default::Default::default()
                }
            }
        }
        impl<'a> ::buffa::ViewEncode<'a> for RunQueryResponseView<'a> {
            #[allow(clippy::needless_borrow, clippy::let_and_return)]
            fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
                #[allow(unused_imports)]
                use ::buffa::Enumeration as _;
                let mut size = 0u32;
                if !self.arrow_ipc.is_empty() {
                    size
                        += 1u32
                            + ::buffa::types::bytes_encoded_len(&self.arrow_ipc) as u32;
                }
                if self.num_rows != 0u64 {
                    size
                        += 1u32
                            + ::buffa::types::uint64_encoded_len(self.num_rows) as u32;
                }
                size += self.__buffa_unknown_fields.encoded_len() as u32;
                size
            }
            #[allow(clippy::needless_borrow)]
            fn write_to(
                &self,
                _cache: &mut ::buffa::SizeCache,
                buf: &mut impl ::buffa::bytes::BufMut,
            ) {
                #[allow(unused_imports)]
                use ::buffa::Enumeration as _;
                if !self.arrow_ipc.is_empty() {
                    ::buffa::encoding::Tag::new(
                            1u32,
                            ::buffa::encoding::WireType::LengthDelimited,
                        )
                        .encode(buf);
                    ::buffa::types::encode_bytes(&self.arrow_ipc, buf);
                }
                if self.num_rows != 0u64 {
                    ::buffa::encoding::Tag::new(
                            2u32,
                            ::buffa::encoding::WireType::Varint,
                        )
                        .encode(buf);
                    ::buffa::types::encode_uint64(self.num_rows, buf);
                }
                self.__buffa_unknown_fields.write_to(buf);
            }
        }
        /// Serializes this view as protobuf JSON.
        ///
        /// Implicit-presence fields with default values are omitted, `required`
        /// fields are always emitted, explicit-presence (`optional`) fields are
        /// emitted only when set, bytes fields are base64-encoded, and enum
        /// values are their proto name strings.
        ///
        /// This impl uses `serialize_map(None)` because the number of emitted
        /// fields depends on default-omission rules; serializers that require
        /// known map lengths (e.g. `bincode`) will return a runtime error.
        /// Use the owned message type for those formats.
        impl<'__a> ::serde::Serialize for RunQueryResponseView<'__a> {
            fn serialize<__S: ::serde::Serializer>(
                &self,
                __s: __S,
            ) -> ::core::result::Result<__S::Ok, __S::Error> {
                use ::serde::ser::SerializeMap as _;
                let mut __map = __s.serialize_map(::core::option::Option::None)?;
                if !::buffa::json_helpers::skip_if::is_empty_bytes(self.arrow_ipc) {
                    struct _W<'__x>(&'__x [u8]);
                    impl ::serde::Serialize for _W<'_> {
                        fn serialize<__S: ::serde::Serializer>(
                            &self,
                            __s: __S,
                        ) -> ::core::result::Result<__S::Ok, __S::Error> {
                            ::buffa::json_helpers::bytes::serialize(self.0, __s)
                        }
                    }
                    __map.serialize_entry("arrowIpc", &_W(self.arrow_ipc))?;
                }
                if !::buffa::json_helpers::skip_if::is_zero_u64(&self.num_rows) {
                    struct _W(u64);
                    impl ::serde::Serialize for _W {
                        fn serialize<__S: ::serde::Serializer>(
                            &self,
                            __s: __S,
                        ) -> ::core::result::Result<__S::Ok, __S::Error> {
                            ::buffa::json_helpers::uint64::serialize(&self.0, __s)
                        }
                    }
                    __map.serialize_entry("numRows", &_W(self.num_rows))?;
                }
                __map.end()
            }
        }
        impl<'a> ::buffa::MessageName for RunQueryResponseView<'a> {
            const PACKAGE: &'static str = "open_lakehouse.query.v1";
            const NAME: &'static str = "RunQueryResponse";
            const FULL_NAME: &'static str = "open_lakehouse.query.v1.RunQueryResponse";
            const TYPE_URL: &'static str = "type.googleapis.com/open_lakehouse.query.v1.RunQueryResponse";
        }
        impl<'v> ::buffa::DefaultViewInstance for RunQueryResponseView<'v> {
            fn default_view_instance<'a>() -> &'a Self
            where
                Self: 'a,
            {
                static VALUE: ::buffa::__private::OnceBox<
                    RunQueryResponseView<'static>,
                > = ::buffa::__private::OnceBox::new();
                VALUE
                    .get_or_init(|| ::buffa::alloc::boxed::Box::new(
                        <RunQueryResponseView<'static>>::default(),
                    ))
            }
        }
        impl ::buffa::ViewReborrow for RunQueryResponseView<'static> {
            type Reborrowed<'b> = RunQueryResponseView<'b>;
            fn reborrow<'b>(this: &'b Self) -> &'b Self::Reborrowed<'b> {
                this
            }
        }
        /** Self-contained, `'static` owned view of a `RunQueryResponse` message.

 Wraps [`::buffa::OwnedView`]`<`[`RunQueryResponseView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`RunQueryResponseView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
        #[derive(Clone, Debug)]
        pub struct RunQueryResponseOwnedView(
            ::buffa::OwnedView<RunQueryResponseView<'static>>,
        );
        impl RunQueryResponseOwnedView {
            /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
            ///
            /// The view borrows directly from the buffer's data; the buffer is
            /// retained inside the returned handle.
            ///
            /// # Errors
            ///
            /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
            /// protobuf data.
            pub fn decode(
                bytes: ::buffa::bytes::Bytes,
            ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
                ::core::result::Result::Ok(
                    RunQueryResponseOwnedView(::buffa::OwnedView::decode(bytes)?),
                )
            }
            /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
            /// max message size).
            ///
            /// # Errors
            ///
            /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
            /// exceeds the configured limits.
            pub fn decode_with_options(
                bytes: ::buffa::bytes::Bytes,
                opts: &::buffa::DecodeOptions,
            ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
                ::core::result::Result::Ok(
                    RunQueryResponseOwnedView(
                        ::buffa::OwnedView::decode_with_options(bytes, opts)?,
                    ),
                )
            }
            /// Build from an owned message via an encode → decode round-trip.
            ///
            /// # Errors
            ///
            /// Returns [`::buffa::DecodeError`] if the re-encoded bytes are
            /// somehow invalid (should not happen for well-formed messages).
            pub fn from_owned(
                msg: &super::super::RunQueryResponse,
            ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
                ::core::result::Result::Ok(
                    RunQueryResponseOwnedView(::buffa::OwnedView::from_owned(msg)?),
                )
            }
            /// Borrow the full [`RunQueryResponseView`] with its lifetime tied to `&self`.
            #[must_use]
            pub fn view(&self) -> &RunQueryResponseView<'_> {
                self.0.reborrow()
            }
            /// Convert to the owned message type.
            #[must_use]
            pub fn to_owned_message(&self) -> super::super::RunQueryResponse {
                self.0.to_owned_message()
            }
            /// The underlying bytes buffer.
            #[must_use]
            pub fn bytes(&self) -> &::buffa::bytes::Bytes {
                self.0.bytes()
            }
            /// Consume the handle, returning the underlying bytes buffer.
            #[must_use]
            pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
                self.0.into_bytes()
            }
            /// Arrow IPC stream bytes for one record batch (schema + batch + EOS). The
            /// first message's bytes carry the schema, so an empty result still yields one
            /// schema-only message. Feeds `ArrowResultStore.append(ipc)` directly.
            ///
            /// Field 1: `arrow_ipc`
            #[must_use]
            pub fn arrow_ipc(&self) -> &'_ [u8] {
                self.0.reborrow().arrow_ipc
            }
            /// Rows in this chunk, so the client can show progress without decoding.
            ///
            /// Field 2: `num_rows`
            #[must_use]
            pub fn num_rows(&self) -> u64 {
                self.0.reborrow().num_rows
            }
        }
        impl ::core::convert::From<::buffa::OwnedView<RunQueryResponseView<'static>>>
        for RunQueryResponseOwnedView {
            fn from(inner: ::buffa::OwnedView<RunQueryResponseView<'static>>) -> Self {
                RunQueryResponseOwnedView(inner)
            }
        }
        impl ::core::convert::From<RunQueryResponseOwnedView>
        for ::buffa::OwnedView<RunQueryResponseView<'static>> {
            fn from(wrapper: RunQueryResponseOwnedView) -> Self {
                wrapper.0
            }
        }
        impl ::core::convert::AsRef<::buffa::OwnedView<RunQueryResponseView<'static>>>
        for RunQueryResponseOwnedView {
            fn as_ref(&self) -> &::buffa::OwnedView<RunQueryResponseView<'static>> {
                &self.0
            }
        }
        impl ::buffa::HasMessageView for super::super::RunQueryResponse {
            type View<'a> = RunQueryResponseView<'a>;
            type ViewHandle = RunQueryResponseOwnedView;
        }
        impl ::serde::Serialize for RunQueryResponseOwnedView {
            fn serialize<__S: ::serde::Serializer>(
                &self,
                __s: __S,
            ) -> ::core::result::Result<__S::Ok, __S::Error> {
                ::serde::Serialize::serialize(&self.0, __s)
            }
        }
    }
    /// Register this package's `Any` type entries and extension entries.
    pub fn register_types(reg: &mut ::buffa::type_registry::TypeRegistry) {
        reg.register_json_any(super::__RUN_QUERY_REQUEST_JSON_ANY);
        reg.register_json_any(super::__RUN_QUERY_RESPONSE_JSON_ANY);
    }
}
#[doc(inline)]
pub use self::__buffa::view::RunQueryRequestView;
#[doc(inline)]
pub use self::__buffa::view::RunQueryRequestOwnedView;
#[doc(inline)]
pub use self::__buffa::view::RunQueryResponseView;
#[doc(inline)]
pub use self::__buffa::view::RunQueryResponseOwnedView;
#[doc(inline)]
pub use self::__buffa::register_types;
