#!/usr/bin/env bash
# Write .cargo/config.toml patching olai-http / olai-store from the local trestle
# checkout. The directory is gitignored so CI (crates.io) is unaffected.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

if ! command -v trestle >/dev/null 2>&1; then
    echo "error: trestle CLI not found on PATH" >&2
    echo "  Install from https://github.com/open-lakehouse/trestle (Homebrew tap or release binary)." >&2
    exit 1
fi

trestle_root="$("$repo_root/dev/scripts/trestle-root.sh")"
olai_http="$trestle_root/crates/olai-http"
olai_store="$trestle_root/crates/olai-store"

mkdir -p "$repo_root/.cargo"
cat >"$repo_root/.cargo/config.toml" <<EOF
# Generated by dev/scripts/configure-trestle-deps.sh — do not commit (.cargo/ is gitignored).
# Patches olai-http / olai-store from the local trestle checkout so builds work when
# crates.io (or a corporate proxy age filter) cannot resolve the published versions.
# CI resolves these crates from crates.io instead.

[patch.crates-io]
olai-http = { path = "$olai_http" }
olai-store = { path = "$olai_store" }
EOF

echo "Wrote $repo_root/.cargo/config.toml"
echo "  trestle root: $trestle_root"
echo "  trestle CLI:  $(command -v trestle) ($(trestle --version))"
