import type { components } from "./uc-api";

// The OpenAPI surface (paths + raw components) generated by openapi-typescript
// from openapi/unity-catalog.yaml (the OSS Unity Catalog REST API, which is what
// the server in environments/ serves). Regenerate with `bun run gen:api`.
export type { components, paths } from "./uc-api";

type Schemas = components["schemas"];

/** A Unity Catalog catalog (top level of the three-level namespace). */
export type CatalogInfo = Schemas["CatalogInfo"];

/** A Unity Catalog schema (second level), child of a catalog. */
export type SchemaInfo = Schemas["SchemaInfo"];

/** A Unity Catalog table (third level), including its column definitions. */
export type TableInfo = Schemas["TableInfo"];

/** A single column of a table. */
export type ColumnInfo = Schemas["ColumnInfo"];

/** A Unity Catalog volume (schema-level), managed or external storage. */
export type VolumeInfo = Schemas["VolumeInfo"];

/** Managed vs external volume discriminator. */
export type VolumeType = Schemas["VolumeType"];

/** A Unity Catalog function (schema-level). */
export type FunctionInfo = Schemas["FunctionInfo"];

/** A Unity Catalog registered model (schema-level). */
export type RegisteredModelInfo = Schemas["RegisteredModelInfo"];

/** A storage/service credential (metastore-level). */
export type CredentialInfo = Schemas["CredentialInfo"];

/** An external location: a storage path + the credential that authorizes it. */
export type ExternalLocationInfo = Schemas["ExternalLocationInfo"];

export type ListCatalogsResponse = Schemas["ListCatalogsResponse"];
export type ListSchemasResponse = Schemas["ListSchemasResponse"];
export type ListTablesResponse = Schemas["ListTablesResponse"];
export type ListVolumesResponse = Schemas["ListVolumesResponseContent"];
export type ListFunctionsResponse = Schemas["ListFunctionsResponse"];
export type ListRegisteredModelsResponse =
  Schemas["ListRegisteredModelsResponse"];
export type ListCredentialsResponse = Schemas["ListCredentialsResponse"];
export type ListExternalLocationsResponse =
  Schemas["ListExternalLocationsResponse"];

/** Request bodies for the create endpoints surfaced in the UI. */
export type CreateCatalog = Schemas["CreateCatalog"];
export type CreateSchema = Schemas["CreateSchema"];
export type CreateVolumeRequestContent = Schemas["CreateVolumeRequestContent"];
export type CreateRegisteredModel = Schemas["CreateRegisteredModel"];
export type CreateCredentialRequest = Schemas["CreateCredentialRequest"];
export type CreateExternalLocation = Schemas["CreateExternalLocation"];
